# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ad4fb18b229f9a2ac22cd624fa26463df52a41b25157e44cf2a2361b177c17fdac92c3e1569c9c792da1bcd4f4bf21404deacbbfd4b0c9680337bc3449cd9b

test:
  secret_key_base: eb1c1b5722d569346d12671e184bd617aefb1a0fa51f0d408a89ad45bb3a5bf9611deefe406ce08eed92f878d74a9619108efcc42fc462277a65ea8abf0033ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
